config/routes.rb
Rails.application.routes.draw do

get 'search', to: 'events#search', as: 'search'
get 'events/results', to: 'events#display', as:'display'
post 'events/search', to: 'events#results', as: 'results'
post 'events/email', to: 'events#email', as: 'email'
post 'users/:id', to: 'users#save', as: 'save'
get 'events/info', to: 'events#info'
  resources :events
  resources :locations
  resources :categories
  resources :users
  resources :admin, only: [:new, :destroy, :delete]

  get '/admin/events', to: 'admin#events'
  get '/admin/users', to: 'admin#users'

  post '/admin/events', to: 'admin#delete'
  post '/admin/users', to: 'admin#remove'

  get '/', to: 'users#home', as:'home'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  post 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :user_events
  has_many :events, through: :user_events

  validates :user_name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only:[:show, :edit, :update, :destroy, :save]
  before_action :authorized, only: [:edit]
  def home
    @events = Event.top_five
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to login_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  def show

  end

  def edit


  end

  def update
    @user = User.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def destroy
    # byebug
    @event = @user.events.find(params["event_id"])

    if @event
      # event.destroy
      @user.events.delete(@event)
      redirect_to @user
    end
  end

  def save
    # binding.pry

    if params["event_id"] != nil
      @event = @@search_results[params["event_id"].to_i]
      @event = Event.find_by(title: @event.title)
      if @event == nil
        @event = @@search_results[params["event_id"].to_i]
        geo = address_to_geo(@event.address)
        @event.location.latitude = geo['lat']
        @event.location.longitude = geo['lng']
        @event.location.neighborhood = geo_to_neighborhood(geo)
        @event.location.save
        @event.save
      end
    else
      @event = Event.find(params["database_event_id"].to_i)
    end

    if !@user.events.include?(@event)
      @user.events << @event
    end

    redirect_to @user
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :full_name, :email, :password)
  end

   def event_params
     # byebug
     event={}
     event["title"] = params["title"]
     event["address"] = params["address"]
     event["description"] = params["description"]
     geo = address_to_geo(event['address'])
     event["location"] = Location.find_or_create_by(latitude:geo['lat'],longitude:geo['lng'],neighborhood:geo_to_neighborhood(geo))
     event["category"] = Category.find_by(name:"Art")
     # params.require(:user).permit(:title, :venue_name, :address, :description)
     event
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<br>
<br>
<br>

<h1>Welcome to EventSpace by DAS</h1>

<h2>Here Are Our Top Five Events:</h2>

<ol class="top-five">
  <% @events.each do |e| %>
    <li><%= link_to e.title, e, 'data-no-turbolink' => true%></li>
  <%end%>
</ol>

app/views/users/new.html.erb
<br>
<br>
<br>

<h1>Sign Up!</h1>

<%= render 'errors/flash_errors' %>

<%= form_for @user do |f| %>
  <table>
    <tr>
      <td><%= f.label :user_name %></td>
      <td><%= f.text_field :user_name %></td>
    </tr>
    <tr>
      <td><%= f.label :full_name %></td>
      <td><%= f.text_field :full_name%></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
</table>
<br>
  <%= f.submit "Sign Up", class: "button" %>
<% end %>

app/views/users/show.html.erb
<br>
<br>
<br>


<h3 class="username"><%= @user.full_name %>'s Events</h3>

<% if current_user.user_name == "admin" %>
  <%= link_to "browser all events", admin_events_path %>
<% end %>

<% if current_user.id == @user.id %>
<ul>
  <% @user.events.each_with_index do |event,i| %>
    <div class="each-event">
      <h3> <%= link_to event.title, event_path(event), 'data-no-turbolink' => true %> </h3>
      <p>Category: <%= event.category.name %> </p>
      <p>Date: <%= event.date %> </p>
      <p>Location: <%= event.location.neighborhood %> </p><br>

      <%= form_tag user_path(@user.id), method: "delete" do %>
      <%= hidden_field_tag "event_id", event.id  %>
      <%= submit_tag "Delete this Event", class: "button" %>
      <% end %>
    </div>
  <% end %>
</ul>
<% end %>