config/routes.rb
Rails.application.routes.draw do

get 'search', to: 'events#search', as: 'search'
get 'events/results', to: 'events#display', as:'display'
post 'events/search', to: 'events#results', as: 'results'
post 'events/email', to: 'events#email', as: 'email'
post 'users/:id', to: 'users#save', as: 'save'
get 'events/info', to: 'events#info'
  resources :events
  resources :locations
  resources :categories
  resources :users
  resources :admin, only: [:new, :destroy, :delete]

  get '/admin/events', to: 'admin#events'
  get '/admin/users', to: 'admin#users'

  post '/admin/events', to: 'admin#delete'
  post '/admin/users', to: 'admin#remove'

  get '/', to: 'users#home', as:'home'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  post 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  belongs_to :category
  has_many :user_events
  has_many :users, through: :user_events

  def self.sort_by_location
    self.all.sort_by{|event| event.location.neighborhood}
  end

  def self.sort_by_date
    self.all.sort_by {|event| event.date}
  end

  def self.by_neighborhood(neighborhood)
    self.all.select {|event| event.location.neighborhood == neighborhood}
  end

  def self.search(search)
     where("name LIKE ? OR description LIKE ? ", "%#{search}%", "%#{search}%")
  end

  def self.top_five

    self.all.uniq.sort_by{|event| event.users.count}[0..4]

  end

end

app/controllers/events_controller.rb
require "./lib/api_parse"
require "./lib/gmail"


class EventsController < ApplicationController

  before_action :get_event, only: [:show]
  def index
    if logged_in?
      @events = Event.all.uniq{|e| e.title}
    else
      redirect_to home_path
    end
  end

  def show
    @user = current_user
    @event.address = "NYC" if @event.address == nil
    @events =[]
    @events << @event
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.location.latitude
      marker.lng event.location.longitude
      marker.infowindow event.title + event.address
    end
    @events = @@search_results
  end

  def email
    @event = Event.find(params[:database_event_id])
    @user = current_user
    # binding.pry
    body = @event.address + "\n"+ @event.date + "\n" + @event.hours + "\n" + @event.description
    mail_that(params["email"], @event.title, body)
    redirect_to @user
  end

  def search
    empty_search

  end

  def info
    # byebug
    @event = @@search_results[params[:id].to_i]
    geo = address_to_geo(@event.address)
    @event.location.latitude = geo['lat']
    @event.location.longitude = geo['lng']
    @event.location.neighborhood = geo_to_neighborhood(geo)
    @events =[]
    # binding.pry
    @search_id = params[:id]
    @events << @event
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.location.latitude
      marker.lng event.location.longitude
      marker.infowindow event.title + event.address
    end
  end

  def results
#if event.category == music // event.category == art
    @user = current_user
    if params[:search].blank?
      flash[:errors] = "Please put a valid search option."
      redirect_to search_path
    else
    geo = address_to_geo(params[:search])

    # binding.pry

    case params["search_type"]
    when "Art"
      data = nyartbeat_parse(geo, 0)
      @events_from_search = data["Events"]["Event"]
      if params["Sort_by"]=="distance"
        @events_from_search.sort_by!{|e| e["Distance"]}
      elsif params["Sort_by"]== "date"
        @events_from_search.sort_by!{|e| e["DateStart"]}
      end
    when "Food"
      if params["Sort_by"]== "distance"
        data = eventbrite(geo)
        @events_from_search = data["events"]
      else
        data = eventbrite(geo, "date")
        @events_from_search = data["events"]
      end
    when "Music"
      data = ticketmaster_parse(geo)
      @events_from_search = data["_embedded"]["events"]
      if params["Sort_by"]=="distance"
        @events_from_search.sort_by!{|e| e["distance"]}
      elsif params["Sort_by"]== "date"
        @events_from_search.sort_by!{|e| e["dates"]["start"]["localDate"]}
      end
    end


    # data = nyartbeat_parse(y, 0)
    # @events_from_search = data["Events"]["Event"]


    if @events_from_search == nil
      flash[:errors] = "Nothing found, please search again."
      redirect_to search_path
    else

      loc = Location.find_or_create_by(latitude:geo['lat'],longitude:geo['lng'])

      case params["search_type"]
      when "Art"
        art = Category.find_or_create_by(name: "Art")

        @events_from_search.each{|e| new_art_event(e,art,loc)} if @@search_results.empty?

      when "Food"
        food = Category.find_or_create_by(name: "Food")

        @events_from_search.each{|e| new_food_event(e, food, loc)} if @@search_results.empty?

      when "Music"
        music = Category.find_or_create_by(name:"Music")
        location = Location.find_or_create_by(latitude:geo['lat'],longitude:geo['lng'])

        @events_from_search.each{|e| new_music_event(e, music, location)} if @@search_results.empty?

      end


    # @events_from_search.each{|e| new_art_event(e)} if @@search_results.empty?

    @events = @@search_results
    redirect_to display_path
    end
  end
  end

  def display
    @user = current_user
    @events = @@search_results
  end

  private


  def new_art_event(event, art, loc)

    hash = {}
    # byebug
    #Change category depending on event category.
    hash["title"]=event["Name"]
    hash["venue"]=event["Venue"]["Name"]
    hash["address"]=event["Venue"]["Address"]
    hash["description"]=event["Description"]
    hash["price"]=event["Venue"]["Price"]
    hash["date"]=Date.strptime(event["DateStart"]).strftime('%a, %B %d, %Y') + " to " +  Date.strptime(event["DateEnd"]).strftime('%a, %B %d, %Y')
    hash["hours"]=Time.strptime(event["Venue"]["OpeningHour"],'%H:%M').strftime('%l:%M %p')+" - "+Time.strptime(event["Venue"]["ClosingHour"],'%H:%M').strftime('%l:%M %p')
    location = Location.new
    location = loc
    hash["location"] = location
    hash["category"] = art
    # byebug
    new_event= Event.new(hash)
    @@search_results << new_event
  end


  def new_food_event(event, food, loc)
    # binding.pry
    hash = {}
    hash["title"]=event["name"]["text"]
    # hash["venue"]=event["Venue"]["Name"]
    hash["address"]=event["venue"]["address"]["localized_address_display"]
    hash["description"]=event["description"]["text"]
    start_time = event["start"]["local"].split("T")
    end_time = event["end"]["local"].split("T")

    hash["date"]=Date.strptime(start_time[0]).strftime('%a, %B %d, %Y') + " to " +  Date.strptime(end_time[0]).strftime('%a, %B %d, %Y')
    hash["hours"]=Time.strptime(start_time[1],'%H:%M').strftime('%l:%M %p')+" - "+Time.strptime(end_time[1],'%H:%M').strftime('%l:%M %p')
    hash["price"]=" "
    location = Location.new

    location.latitude = event["venue"]["address"]["latitude"].to_f
    location.longitude = event["venue"]["address"]["longitude"].to_f

    hash["category"] = food
    hash["location"] = location

    new_event= Event.new(hash)
    @@search_results << new_event
  end

  def new_music_event(event, music, location)
    hash = {}

    hash["title"]=event["name"]
    hash["venue"]=event["_embedded"]["venues"][0]["name"]
    hash["address"]=event["_embedded"]["venues"][0]["address"]["line1"] + ", " + event["_embedded"]["venues"][0]["city"]["name"] + ", " + event["_embedded"]["venues"][0]["state"]["stateCode"]
    hash["description"]=event["url"]
    hash["price"]="$" + event["priceRanges"][0]["min"].to_s + "0" + " to " + "$" + event["priceRanges"][0]["max"].to_s + "0"
    hash["date"]=Date.strptime(event["dates"]["start"]["localDate"]).strftime('%a, %B %d, %Y') + " to " +  Date.strptime(event["dates"]["start"]["localDate"]).strftime('%a, %B %d, %Y')
    hash["hours"]=Time.strptime(event["dates"]["start"]["localTime"],'%H:%M').strftime('%l:%M %p')
    hash["category"] = music
    location = Location.new
    location.longitude = event["_embedded"]["venues"][0]["location"]["longitude"]
    location.latitude = event["_embedded"]["venues"][0]["location"]["latitude"]
    hash["location"] = location


    new_event= Event.new(hash)
    @@search_results << new_event

  end

  def get_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/display.html.erb
<br>
<br>
<br>


<h1>Here Are Your Results:</h1>


<% @events.each_with_index do |event_data, i|%>
<div class="display-page">
  <div class="each-event">

    <h3><%= link_to event_data["title"], controller: "events", action: "info", id: i, 'data-no-turbolink' => true %></h3>
    <p>Venue: <%= event_data["venue"]%></p>
    <p>Address: <%= event_data["address"] %></p>
    <p>Hours: <%= event_data["hours"] %></p>
    <p>Date: <%= event_data["date"] %></p>
    <p>Price: <%= event_data["price"] %></p>

    <p><%= truncate(event_data["description"], length: 300, separator: " ")%>
      <%= link_to "See more", controller: "events", action: "info", id: i, 'data-no-turbolink' => true %>
     </p>
    <%= form_tag save_path(@user.id), method: 'post' do%>
      <%= hidden_field_tag "event_id", i %>
      <%= submit_tag "Save Event", class: "button" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/events/index.html.erb
<br>
<br>
<br>

<h1>Check out all these events</h1>

<ul>
  <% @events.each do |event| %>
    <div class="each-event">
      <h3><%= link_to event.title, event_path(event), 'data-no-turbolink' => true %> </h3>
      <p>Location: <%= event.location.neighborhood %> </p><br>
    </div>
  <% end %>

</ul>

app/views/events/info.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCQnku5y5GTSrMwE7LH_eB2wJVgM7jbpZ8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<br>
<br>
<br>

<div class="each-event">
  <h3><%= @event.title %></h3>

  <p>Address: <%=@event.address%> </p>
  <p>Neighborhood: <%= @event.location.neighborhood %> </p>
  <p>Description: <%= @event.description%> </p>

  <%= form_tag save_path(current_user), method: 'post' do%>
    <%= hidden_field_tag "event_id", @search_id %>
    <%= submit_tag "Save Event", class: "button" %>
  <% end %>
</div>

<div style='width: 900px;'>
  <div id="map" style='width: 900px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {maxZoom: 15}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

</script>

<%= link_to "Back to Results", display_path %>

app/views/events/results.html.erb
<h1>Here Are Your Results:</h1>


<% @events.each do |event_data|%>
<div>
  <h2><%= event_data["title"] %></h2>
  <%= event_data["venue"]%>
  <%= event_data["address"] %>
  <%= event_data["address"] %>

  <p><%= truncate(event_data["description"], length: 300, separator: " ")


   %></p>
  <%= form_tag save_path(@user.id), method: 'post' do%>
    <%= submit_tag "Save Event", class: "button" %>
  <% end %>
</div>
<% end %>
<% if flash[:errors] %><br>
<h3> <%= flash[:errors] %></h3>
<% end %>

app/views/events/search.html.erb
<br>
<br>
<br>


<%= form_tag results_path, :method => 'post' do %>
<span class="search"><%= text_field_tag :search, params[:search], placeholder: 'Enter the Location Here' %></span>
<%= radio_button_tag 'search_type', 'Art' %> <label for="Art">Art</label>
<%= radio_button_tag 'search_type', 'Food' %>  <label for="Food">Food</label>
<%= radio_button_tag 'search_type', 'Music' %>  <label for="Music">Music</label> 



<!-- <%= radio_button_tag 'sort_search', 'Distance' %> <label for="Distance">Search By Distance</label>
<%= radio_button_tag 'sort_search', 'Date' %> <label for="Date">Search By Date</label> -->


<!-- <%= radio_button_tag 'search_type', 'Music' %>  <label for="Music">Music</label> -->
<!-- <%= radio_button_tag 'distance_type', 'Distance' %> <label for="Distance">Search By Distance</label>
<%= radio_button_tag 'date_type', 'Date' %> <label for="Date">Search By Date</label> -->
<!-- <option value=" " selected>Select an Option</option> -->

<span>Sort by: <select name="Sort_by">
  <option value="distance">Distance</option>
  <option value="date">Date</option>
</select>




<%= submit_tag 'Search'%>
<% end %>

<br>

<% if flash[:errors] %><br>
<h3> <%= flash[:errors] %></h3>
<% end %>

<br>

<iframe src="https://giphy.com/embed/JIX9t2j0ZTN9S" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/JIX9t2j0ZTN9S"></a></p>

app/views/events/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCQnku5y5GTSrMwE7LH_eB2wJVgM7jbpZ8"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<br>
<br>
<br>


<h3 class="show-title"><%= @event.title %></h3>

<div class="show-attributes">
  <div class="each-event">
  <p>Date: <%= @event.date %> </p>
  <p>Address: <%=@event.address%> </p>
  <p>Neighborhood: <%= @event.location.neighborhood %> </p>
  <p>Description: <%= @event.description%> </p>

  <% if !@user.events.include?(@event) %>
  <%= form_tag save_path(current_user), method: 'post' do%>
    <%= hidden_field_tag "database_event_id", @event.id %>
    <%= submit_tag "Save Event", class: "button" %>
  <% end %>
  <% end %>

  <br>

  <%= form_tag email_path(@event), method: 'post' do %>
  <span>Email event info: <%= email_field_tag 'email', current_user.email %>
  <%= hidden_field_tag "database_event_id", @event.id %>
  <%= submit_tag "Send" %></span>
  <% end %>
  <br>
  </div>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {maxZoom: 15}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

</script>

<div class="links">
  <% if @events.count >0 %>
  <p><%= link_to "Back to Search Results", display_path %></p>
  <% end %>
  <p><%= link_to "All Events", events_path %></p>
</div>