config/routes.rb
Rails.application.routes.draw do

get 'search', to: 'events#search', as: 'search'
get 'events/results', to: 'events#display', as:'display'
post 'events/search', to: 'events#results', as: 'results'
post 'events/email', to: 'events#email', as: 'email'
post 'users/:id', to: 'users#save', as: 'save'
get 'events/info', to: 'events#info'
  resources :events
  resources :locations
  resources :categories
  resources :users
  resources :admin, only: [:new, :destroy, :delete]

  get '/admin/events', to: 'admin#events'
  get '/admin/users', to: 'admin#users'

  post '/admin/events', to: 'admin#delete'
  post '/admin/users', to: 'admin#remove'

  get '/', to: 'users#home', as:'home'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  post 'logout', to: 'sessions#destroy', as: 'logout'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventSpaceNyc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="main-nav">
      <ul>
        <% if logged_in? %>
          <p>Hello, <%=current_user.user_name  %></p>
          <li><%= link_to "SHOW ALL SAVED EVENTS", current_user %></li>
          <li><%= link_to "LOG OUT", logout_path, method: :post %></li>
          <li><%= link_to "SEARCH", search_path %></li>
          <li><%= link_to "HOME", home_path %></li>

        <% else %>
          <li><%= link_to "SIGN UP", signup_path %></li>
          <li><%= link_to "LOGIN", login_path %></li>
          <li><%= link_to "HOME", home_path %></li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>